import { LogoItem } from "@/components/LogoCarousel/LogoItem";

export const LogoCarousel = () => {
  return (
    <div className="text-sm box-border caret-transparent leading-[22.4px] [mask-image:linear-gradient(to_right,rgba(0,0,0,0)_1%,rgb(0,0,0)_10%,rgb(0,0,0)_90%,rgba(0,0,0,0)_99%)] [mask-repeat:no-repeat] [mask-size:contain] outline-[3px] w-full [mask-composite:exclude] overflow-hidden [mask-position:50%] py-5 md:text-base md:leading-[25.6px] md:py-10">
      <div className="relative text-sm box-border caret-transparent h-full leading-[22.4px] outline-[3px] w-full mx-auto md:text-base md:leading-[25.6px]">
        <div className="relative text-sm items-stretch box-border caret-transparent gap-x-3.5 flex h-full justify-start leading-[22.4px] max-w-full outline-[3px] gap-y-3.5 translate-x-[-1419.9px] w-full md:text-base md:gap-x-4 md:leading-[25.6px] md:gap-y-4 md:translate-x-[-1410.38px]">
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-2.svg"
            imageAlt=""
            isLink={true}
            href="https://www.bbb.org/us/co/denver/profile/plumber/heart-hcpe-group-llc-1296-1000194172/#sealclick"
            imageVariantClass=""
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-3.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[71px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-4.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[107px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-5.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[101px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-6.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[98px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-7.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[68px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/blue-seal-96-50-bbb-1000194172.png"
            imageAlt=""
            isLink={true}
            href="https://www.bbb.org/us/co/denver/profile/plumber/heart-hcpe-group-llc-1296-1000194172/#sealclick"
            imageVariantClass=""
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/angi_logo.png"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[71px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/logo-ontoplist.png"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[107px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/tdl_logo.png"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[101px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/thornton-area-chamber-of-commerce-member.png"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[98px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/west-metro-chamber-logo.png"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[68px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/blue-seal-96-50-bbb-1000194172.png"
            imageAlt=""
            isLink={true}
            href="https://www.bbb.org/us/co/denver/profile/plumber/heart-hcpe-group-llc-1296-1000194172/#sealclick"
            imageVariantClass=""
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-3.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[71px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-4.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[107px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-5.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[101px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-6.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[98px]"
          />
          <LogoItem
            imageSrc="https://c.animaapp.com/moump05judxXNB/assets/image-7.svg"
            imageAlt=""
            isLink={false}
            href=""
            imageVariantClass="w-[68px]"
          />
        </div>
      </div>
    </div>
  );
};
